name: Sync Upstream

on:
  schedule:
    - cron: '5 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/1c7/chinese-independent-developer.git || true
          git fetch upstream --prune

      - name: Merge upstream/master
        run: |
          git checkout master                  
          git merge upstream/master --no-edit --no-ff || echo "Merge conflict or already up to date"

      - name: Check if there are changes
        id: check_changes
        run: |
          if git diff --quiet origin/master; then
            echo "No new changes from upstream."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Found changes from upstream."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push if changed
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin master
